import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

declare var chrome: any;

const MOUNT_POINT_ID = 'smartcompare-ai-extension-host';

console.log('[SmartCompare] Content script loaded. Waiting for trigger...');

// Check if already injected
if (!document.getElementById(MOUNT_POINT_ID)) {
  
  // 1. Create the Host Element
  const hostElement = document.createElement('div');
  hostElement.id = MOUNT_POINT_ID;
  
  Object.assign(hostElement.style, {
    position: 'fixed',
    top: '0',
    left: '0',
    width: '0',
    height: '0',
    zIndex: '2147483647',
    pointerEvents: 'none'
  });

  document.body.appendChild(hostElement);

  // 2. Create Shadow DOM
  const shadowRoot = hostElement.attachShadow({ mode: 'open' });

  // 3. Create the React Root
  const appRoot = document.createElement('div');
  appRoot.id = 'smartcompare-app-root';
  appRoot.style.pointerEvents = 'auto'; 
  shadowRoot.appendChild(appRoot);

  // 4. Inject Styles
  // Dynamically load the stylesheet generated by the 'popup' entry
  const cssUrl = chrome.runtime.getURL('popup.css');
  console.log('[SmartCompare] Injecting styles from:', cssUrl);
  
  const linkElement = document.createElement('link');
  linkElement.rel = 'stylesheet';
  linkElement.href = cssUrl;
  shadowRoot.appendChild(linkElement);

  // Add global font to main document (Shadow DOM cannot easily load remote fonts reliably without CORS issues on some sites)
  const fontLink = document.createElement('link');
  fontLink.href = 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap';
  fontLink.rel = 'stylesheet';
  if (!document.querySelector(`link[href="${fontLink.href}"]`)) {
    document.head.appendChild(fontLink);
  }

  // Internal resets
  const resetStyle = document.createElement('style');
  resetStyle.textContent = `
    :host { 
      all: initial; 
      font-family: 'Inter', sans-serif;
    }
    #smartcompare-app-root {
      position: relative;
      width: 100%;
      height: 100%;
    }
  `;
  shadowRoot.appendChild(resetStyle);

  // 5. Mount React App
  const root = createRoot(appRoot);
  root.render(<App isExtensionOverride={true} />);

  // 6. Listener
  chrome.runtime.onMessage.addListener((request: any, sender: any, sendResponse: any) => {
    if (request.action === "TOGGLE_OVERLAY") {
      console.log('[SmartCompare] Toggle action received.');
      window.dispatchEvent(new CustomEvent('SMARTCOMPARE_TOGGLE'));
    }
  });
}